### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ace18o** [Th3Shadowbroker/AtMessage#2]
Currently using Spigot version: 1.9.2
Current version of plugin being used: r_1.0.4
Error from console: http://pastebin.com/caj8seHv

**Comment by Th3Shadowbroker** [comment]
Hey @Ace18o,
thanks for your report ^^
I've implemented backward compatibility to 1.9.2
[Download it from here](https://www.spigotmc.org/resources/message.22935/history)
